#!/usr/bin/perl

=head1 NAME

deny_bounce - Make sure that no bounce Messages are let through.

=head1 DESCRIPTION

Rejects messages that comply with a RFC 3464.

=head1 CONFIGURATION

Nothing I know of

=head1 AUTHOR

abusix http://www.abusix.org
(ts) info [at] abusix.org

=head1 LICENSE

Copyright (C) 2009-2010 abusix 

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

=cut

sub register {
    my ( $self, $qp, @args ) = @_;

}

sub hook_mail {
    my ( $self, $transaction, $sender ) = @_;

    # $sender: an Qpsmtpd::Address object for sender of the message

    return ( DENY_DISCONNECT, "We dont accept Mailer Daemon Mails" )
      unless ( $sender->address =~ /\@/ );

    return (OK);
}

sub hook_data_post {
    my ( $self, $transaction ) = @_;

    if ( $self->qp->transaction->header ) {

        if ( $self->qp->transaction->header->get('Content-Type') ) {
            return ( DENY_DISCONNECT, "We dont accept Mailer Daemon Mails" )
              if ( $self->qp->transaction->header->get('Content-Type') =~
                /report\-type=delivery\-status/ );
        }
    }

    # Dont do any actions -> decline action
    return (DECLINED);
}
